### ISSUE TITLE
Integer project on Heroku

### ISSUE THREAD

**Issue by sebglon** [sebglon/docker-consultant#1]

**Comment by sebglon** [comment]
I have this error ; this is du tu express 4

```
2015-10-14T12:18:06.486600+00:00 app[web.1]:       throw new Error('Most middleware (like ' + name + ') is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.');
2015-10-14T12:18:06.486603+00:00 app[web.1]:       ^
2015-10-14T12:18:06.486604+00:00 app[web.1]: 
2015-10-14T12:18:06.486606+00:00 app[web.1]: Error: Most middleware (like logger) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
2015-10-14T12:18:06.486608+00:00 app[web.1]:     at Function.Object.defineProperty.get (/app/node_modules/express/lib/express.js:99:13)
2015-10-14T12:18:06.486609+00:00 app[web.1]:     at Object.<anonymous> (/app/web.js:5:18)
2015-10-14T12:18:06.486610+00:00 app[web.1]:     at Module._compile (module.js:435:26)
2015-10-14T12:18:06.486612+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:442:10)
2015-10-14T12:18:06.486613+00:00 app[web.1]:     at Module.load (module.js:356:32)
2015-10-14T12:18:06.486614+00:00 app[web.1]:     at Function.Module._load (module.js:311:12)
2015-10-14T12:18:06.486615+00:00 app[web.1]:     at Function.Module.runMain (module.js:467:10)
2015-10-14T12:18:06.486617+00:00 app[web.1]:     at startup (node.js:134:18)
2015-10-14T12:18:06.486618+00:00 app[web.1]:     at node.js:961:3
2015-10-14T12:18:07.415379+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by sebglon** [comment]
Change file we.js to use new express config:

```
var gzippo = require('gzippo');
var express = require('express');
var PORT = process.env.PORT || 3000;

var app = express();
app.listen(PORT, onListen);
 app.use(gzippo.staticGzip("" + __dirname + "/dist"));

function onListen() {
  console.log('Listening on', PORT);
}
```

**Comment by sebglon** [comment]
yo angular docker-consultant # create project 
npm install gzippo express --save # add dependency for Heroku
vi web.js # to define server

```
var gzippo = require('gzippo');
  var express = require('express');
  var app = express();

  app.use(express.logger('dev'));
  app.use(gzippo.staticGzip("" + __dirname + "/dist"));
  app.listen(process.env.PORT || 5000);
```

vi Procfile # for Heroku to start server

```
web: node web.js
```
